spring:
  cloud:
    nacos:
      discovery:
        ###服务注册地址
        server-addr: 127.0.0.1:8848
  application:
    name: nacos-service-server-data
server:
  port: 8081

logging:
  path: F:/idea_workspace/springboot-nacos/logs/${spring.application.name}
